// Generated by rstantools.  Do not edit by hand.

/*
    rstanlm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rstanlm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rstanlm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_sas_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_sas");
    reader.add_event(54, 52, "end", "model_sas");
    return reader;
}
template <typename T0__, typename T1__>
typename boost::math::tools::promote_args<T0__, T1__>::type
besselK(const T0__& v,
            const T1__& z, std::ostream* pstream__);
template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
sinh_arcsin_lpdf(const T0__& y,
                     const T1__& mu,
                     const T2__& sigma,
                     const T3__& epsilon,
                     const T4__& delta, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 5;
        return stan::math::promote_scalar<fun_return_scalar_t__>(((((normal_log(stan::math::sinh(((delta * stan::math::asinh(((y - mu) / sigma))) - epsilon)), 0, 1) + stan::math::log(delta)) - (0.5 * stan::math::log((1 + (pow((y - mu), 2) / pow(sigma, 2)))))) - stan::math::log(sigma)) + stan::math::log(stan::math::cosh(((delta * stan::math::asinh(((y - mu) / sigma))) - epsilon)))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
sinh_arcsin_lpdf(const T0__& y,
                     const T1__& mu,
                     const T2__& sigma,
                     const T3__& epsilon,
                     const T4__& delta, std::ostream* pstream__) {
    return sinh_arcsin_lpdf<false>(y,mu,sigma,epsilon,delta, pstream__);
}
struct sinh_arcsin_lpdf_functor__ {
    template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& y,
                     const T1__& mu,
                     const T2__& sigma,
                     const T3__& epsilon,
                     const T4__& delta, std::ostream* pstream__) const {
        return sinh_arcsin_lpdf(y, mu, sigma, epsilon, delta, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__, class RNG>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
sinh_arcsin_rng(const T0__& mu,
                    const T1__& sigma,
                    const T2__& epsilon,
                    const T3__& delta, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 10;
        return stan::math::promote_scalar<fun_return_scalar_t__>((mu + (sigma * stan::math::sinh(((stan::math::asinh(normal_rng(0, 1, base_rng__)) + epsilon) / delta)))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct sinh_arcsin_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, class RNG>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& mu,
                    const T1__& sigma,
                    const T2__& epsilon,
                    const T3__& delta, RNG& base_rng__, std::ostream* pstream__) const {
        return sinh_arcsin_rng(mu, sigma, epsilon, delta, base_rng__, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_sas : public prob_grad {
private:
        int K;
        std::vector<double> yi;
        std::vector<double> si;
public:
    model_sas(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_sas(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_sas_namespace::model_sas";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 0);
            current_statement_begin__ = 15;
            validate_non_negative_index("yi", "K", K);
            context__.validate_dims("data initialization", "yi", "double", context__.to_vec(K));
            yi = std::vector<double>(K, double(0));
            vals_r__ = context__.vals_r("yi");
            pos__ = 0;
            size_t yi_k_0_max__ = K;
            for (size_t k_0__ = 0; k_0__ < yi_k_0_max__; ++k_0__) {
                yi[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 16;
            validate_non_negative_index("si", "K", K);
            context__.validate_dims("data initialization", "si", "double", context__.to_vec(K));
            si = std::vector<double>(K, double(0));
            vals_r__ = context__.vals_r("si");
            pos__ = 0;
            size_t si_k_0_max__ = K;
            for (size_t k_0__ = 0; k_0__ < si_k_0_max__; ++k_0__) {
                si[k_0__] = vals_r__[pos__++];
            }
            size_t si_i_0_max__ = K;
            for (size_t i_0__ = 0; i_0__ < si_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "si[i_0__]", si[i_0__], 0);
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 19;
            num_params_r__ += 1;
            current_statement_begin__ = 20;
            num_params_r__ += 1;
            current_statement_begin__ = 21;
            num_params_r__ += 1;
            current_statement_begin__ = 22;
            num_params_r__ += 1;
            current_statement_begin__ = 23;
            validate_non_negative_index("theta", "K", K);
            num_params_r__ += (1 * K);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_sas() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 19;
        if (!(context__.contains_r("mu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu", "double", context__.to_vec());
        double mu(0);
        mu = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 20;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 21;
        if (!(context__.contains_r("epsilon")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable epsilon missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("epsilon");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "epsilon", "double", context__.to_vec());
        double epsilon(0);
        epsilon = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(epsilon);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable epsilon: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 22;
        if (!(context__.contains_r("delta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable delta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("delta");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "delta", "double", context__.to_vec());
        double delta(0);
        delta = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1000, delta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable delta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 23;
        if (!(context__.contains_r("theta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta");
        pos__ = 0U;
        validate_non_negative_index("theta", "K", K);
        context__.validate_dims("parameter initialization", "theta", "double", context__.to_vec(K));
        std::vector<double> theta(K, double(0));
        size_t theta_k_0_max__ = K;
        for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
            theta[k_0__] = vals_r__[pos__++];
        }
        size_t theta_i_0_max__ = K;
        for (size_t i_0__ = 0; i_0__ < theta_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_unconstrain(theta[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 19;
            local_scalar_t__ mu;
            (void) mu;  // dummy to suppress unused var warning
            if (jacobian__)
                mu = in__.scalar_constrain(lp__);
            else
                mu = in__.scalar_constrain();
            current_statement_begin__ = 20;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 21;
            local_scalar_t__ epsilon;
            (void) epsilon;  // dummy to suppress unused var warning
            if (jacobian__)
                epsilon = in__.scalar_constrain(lp__);
            else
                epsilon = in__.scalar_constrain();
            current_statement_begin__ = 22;
            local_scalar_t__ delta;
            (void) delta;  // dummy to suppress unused var warning
            if (jacobian__)
                delta = in__.scalar_lub_constrain(0, 1000, lp__);
            else
                delta = in__.scalar_lub_constrain(0, 1000);
            current_statement_begin__ = 23;
            std::vector<local_scalar_t__> theta;
            size_t theta_d_0_max__ = K;
            theta.reserve(theta_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < theta_d_0_max__; ++d_0__) {
                if (jacobian__)
                    theta.push_back(in__.scalar_constrain(lp__));
                else
                    theta.push_back(in__.scalar_constrain());
            }
            // model body
            current_statement_begin__ = 26;
            for (int i = 1; i <= K; ++i) {
                current_statement_begin__ = 27;
                lp_accum__.add(normal_log<propto__>(get_base1(yi, i, "yi", 1), get_base1(theta, i, "theta", 1), get_base1(si, i, "si", 1)));
            }
            current_statement_begin__ = 29;
            for (int i = 1; i <= K; ++i) {
                current_statement_begin__ = 30;
                lp_accum__.add(sinh_arcsin_lpdf<propto__>(get_base1(theta, i, "theta", 1), mu, sigma, epsilon, delta, pstream__));
            }
            current_statement_begin__ = 32;
            lp_accum__.add(normal_log<propto__>(mu, 0, 100));
            current_statement_begin__ = 33;
            lp_accum__.add(uniform_log<propto__>(sigma, 0, 20));
            current_statement_begin__ = 34;
            lp_accum__.add(normal_log<propto__>(epsilon, 0, 4));
            current_statement_begin__ = 35;
            lp_accum__.add(uniform_log<propto__>(delta, 0, 20));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("mu");
        names__.push_back("sigma");
        names__.push_back("epsilon");
        names__.push_back("delta");
        names__.push_back("theta");
        names__.push_back("sx_post_mean");
        names__.push_back("sx_post_m2");
        names__.push_back("sx_post_var");
        names__.push_back("x_post_mean");
        names__.push_back("x_post_var");
        names__.push_back("theta_new");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_sas_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double mu = in__.scalar_constrain();
        vars__.push_back(mu);
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);
        double epsilon = in__.scalar_constrain();
        vars__.push_back(epsilon);
        double delta = in__.scalar_lub_constrain(0, 1000);
        vars__.push_back(delta);
        std::vector<double> theta;
        size_t theta_d_0_max__ = K;
        theta.reserve(theta_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < theta_d_0_max__; ++d_0__) {
            theta.push_back(in__.scalar_constrain());
        }
        size_t theta_k_0_max__ = K;
        for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
            vars__.push_back(theta[k_0__]);
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 38;
            double sx_post_mean;
            (void) sx_post_mean;  // dummy to suppress unused var warning
            stan::math::initialize(sx_post_mean, DUMMY_VAR__);
            stan::math::fill(sx_post_mean, DUMMY_VAR__);
            current_statement_begin__ = 39;
            double sx_post_m2;
            (void) sx_post_m2;  // dummy to suppress unused var warning
            stan::math::initialize(sx_post_m2, DUMMY_VAR__);
            stan::math::fill(sx_post_m2, DUMMY_VAR__);
            current_statement_begin__ = 40;
            double sx_post_var;
            (void) sx_post_var;  // dummy to suppress unused var warning
            stan::math::initialize(sx_post_var, DUMMY_VAR__);
            stan::math::fill(sx_post_var, DUMMY_VAR__);
            current_statement_begin__ = 41;
            double x_post_mean;
            (void) x_post_mean;  // dummy to suppress unused var warning
            stan::math::initialize(x_post_mean, DUMMY_VAR__);
            stan::math::fill(x_post_mean, DUMMY_VAR__);
            current_statement_begin__ = 42;
            double x_post_var;
            (void) x_post_var;  // dummy to suppress unused var warning
            stan::math::initialize(x_post_var, DUMMY_VAR__);
            stan::math::fill(x_post_var, DUMMY_VAR__);
            current_statement_begin__ = 43;
            double theta_new;
            (void) theta_new;  // dummy to suppress unused var warning
            stan::math::initialize(theta_new, DUMMY_VAR__);
            stan::math::fill(theta_new, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 44;
            stan::math::assign(sx_post_mean, (((stan::math::sinh((epsilon / delta)) * stan::math::exp(0.25)) / stan::math::sqrt((8.0 * stan::math::pi()))) * (besselK((((1.0 / delta) + 1.0) * 0.5), 0.25, pstream__) + besselK((((1.0 / delta) - 1.0) * 0.5), 0.25, pstream__))));
            current_statement_begin__ = 46;
            stan::math::assign(sx_post_m2, (0.5 * ((((stan::math::cosh(((2.0 * epsilon) / delta)) * stan::math::exp(0.25)) / stan::math::sqrt((8.0 * stan::math::pi()))) * (besselK((((2.0 / delta) + 1.0) * 0.5), 0.25, pstream__) + besselK((((2.0 / delta) - 1.0) * 0.5), 0.25, pstream__))) - 1.0)));
            current_statement_begin__ = 48;
            stan::math::assign(sx_post_var, (sx_post_m2 - pow(sx_post_mean, 2)));
            current_statement_begin__ = 49;
            stan::math::assign(x_post_mean, ((sigma * sx_post_mean) + mu));
            current_statement_begin__ = 50;
            stan::math::assign(x_post_var, (pow(sigma, 2) * sx_post_var));
            current_statement_begin__ = 51;
            stan::math::assign(theta_new, sinh_arcsin_rng(mu, sigma, epsilon, delta, base_rng__, pstream__));
            // validate, write generated quantities
            current_statement_begin__ = 38;
            vars__.push_back(sx_post_mean);
            current_statement_begin__ = 39;
            vars__.push_back(sx_post_m2);
            current_statement_begin__ = 40;
            vars__.push_back(sx_post_var);
            current_statement_begin__ = 41;
            vars__.push_back(x_post_mean);
            current_statement_begin__ = 42;
            vars__.push_back(x_post_var);
            current_statement_begin__ = 43;
            vars__.push_back(theta_new);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_sas";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "epsilon";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "delta";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_k_0_max__ = K;
        for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sx_post_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sx_post_m2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sx_post_var";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "x_post_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "x_post_var";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_new";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "epsilon";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "delta";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_k_0_max__ = K;
        for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sx_post_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sx_post_m2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sx_post_var";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "x_post_mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "x_post_var";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_new";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_sas_namespace::model_sas stan_model;
#endif
